name: lint and test flask app
on: [push] # sur n'importe quelle branche
jobs: # début de sjobs
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7 # Celui gui fait un "git pull" au sein du runner
      - name: Setup python # Action fournie par githubactions catalogue pour setpup le python
        uses: actions/setup-python@v7
        with:
          python-version: "3.10" # si on mets 3.10 sans double côte, des versions comme 3.10 2.10 seront prise en compte comme 3.1 & 2.1
      - name: install dependencies # installer les prérequis
        run: pip install -r requirements.txt flake8
      - name: run flake 8 # Lancer le teste Lint
        run: flake8 .
  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Setup python
        uses: actions/setup-python@v7
        with:
          python-version: "3.10"
      - name: install dependencies
        run: pip install -r requirements.txt 
      - name: run tests
        run: pytest -m "not integration"      
        # "run" exécute la commande dans le shell de la machine Ubuntu
        # pytest : lance les tests trouvés dans les fichiers test_*.py (ex : test_app.py)
        # -m : filtre les tests selon leur marker
        # "not integration" : exclut les tests marqués @pytest.mark.integration
        # -> test_health et test_hello s'exécutent
        # -> test_dbtest est ignoré (il a besoin de la BDD via Docker Compose)
        # test_app.py : @pytest.mark.integration :
          # mark = marquage
          # marque = integration

    needs: lint # Définir la dépendace, ce job se lencera après la dépendance, c'est à dire, le job test se lance après le job lint
  
  docker-test:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v7
      - name: Build Docker Image
        run: docker build -t monapp:latest .
      - name: Run Docker container
        run: docker run -d --name monapp_test -p 5000:5000 monapp:latest
      - name: Check Container Status
        run: docker ps --filter name==monapp_test
      - name: Test Container response
        run: |
          sleep 5
          curl -f http://localhost:5000/health
      - name: Stop and remove container
        run: |
          docker stop monapp_test
          docker rm monapp_test
