name: Docker Publish to GHCR # Nom du workflow affiché dans l'onglet Actions

on:
  workflow_dispatch: # Lancement manuel depuis l'interface GitHub
  workflow_run: # Lancement après la fin d'un autre workflow
  workflow: ["lint and test flask app"] # Workflow parent à surveiller
  types:
    - completed # Déclenché à la fin du workflow parent, succès ou échec

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Runner Linux hébergé par GitHub
    permissions: # Droits accordés au GITHUB_TOKEN
      contents: read # Lecture du code pour le checkout
      packages: write # Écriture sur GHCR pour le push de l'image

    steps:
      - name: Checkout code
        uses: actions/checkout@v7 # Récupère le code du dépôt sur le runner
      - name: Docker login to GHCR
        uses: docker/login-action@v4 # Connexion au registery de container de Github
        with:
          registry: ghcr.io # Registre de Github, ça peut être un autre registry on-premise ou bin ed'autre type de registry
          username: ${{ github.actor }} # le nom du compte GitHub qui a déclenché le workflow.
          password: ${{ secrets.GITHUB_TOKEN }} # Jeton temporaire généré automatiquement par GitHub pour ce job

      - name: Build Docker Image
        run: docker build -t ghcr.io/azizi-sajjad/saz-linter-python-flask/monapp:latest . # Construit l'image à partir du Dockerfile
      - name: Push Docker Image to GHCR
        run: docker push ghcr.io/azizi-sajjad/saz-linter-python-flask/monapp:latest # Envoie l'image sur GHCR